### ISSUE TITLE
WTB `git push`

### ISSUE THREAD

**Issue by JonDum** [maxkorp/Courier#1]
Push what ya got, I'll fix/get it working from there.

**Comment by maxkorp** [comment]
Now I have to remember where I left this. Whatever changes I had are definitely lost however.

**Comment by JonDum** [comment]
How do you lose code?? :( :-1:

**Comment by maxkorp** [comment]
By changing computers lol. I switched to a new laptop 20 minutes before driving to another state and missed backing that folder up.

**Comment by JonDum** [comment]
Surely Dustin has a copy then. He usually clones the whole drive before wiping.

**Comment by maxkorp** [comment]
Nein, DoD grade nuked stuff beforehand :(

**Comment by JonDum** [comment]
Ok you're officially a poohead. I'm cloning this shiz now and will muck with it till I have it working.

**Comment by maxkorp** [comment]
Cool. I'll write up some issues today after an internal release I'm doing for something else. That way the roadmap is visible.

**Comment by JonDum** [comment]
Tight. I'll let you know what kind of crap I have to go through to get it working on a fresh clone and maybe my thoughts on the public facing api/usage and what I can work on.
